// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package videopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	//Client Stream
	Upload(ctx context.Context, opts ...grpc.CallOption) (VideoService_UploadClient, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (VideoService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VideoService_serviceDesc.Streams[0], "/VideoService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoServiceUploadClient{stream}
	return x, nil
}

type VideoService_UploadClient interface {
	Send(*VideoUploaderRequest) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type videoServiceUploadClient struct {
	grpc.ClientStream
}

func (x *videoServiceUploadClient) Send(m *VideoUploaderRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *videoServiceUploadClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility
type VideoServiceServer interface {
	//Client Stream
	Upload(VideoService_UploadServer) error
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServiceServer struct {
}

func (UnimplementedVideoServiceServer) Upload(VideoService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	s.RegisterService(&_VideoService_serviceDesc, srv)
}

func _VideoService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoServiceServer).Upload(&videoServiceUploadServer{stream})
}

type VideoService_UploadServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*VideoUploaderRequest, error)
	grpc.ServerStream
}

type videoServiceUploadServer struct {
	grpc.ServerStream
}

func (x *videoServiceUploadServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *videoServiceUploadServer) Recv() (*VideoUploaderRequest, error) {
	m := new(VideoUploaderRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VideoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _VideoService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/video.proto",
}
