// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package imagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	//Server Stream
	Download(ctx context.Context, in *ImageDownloaderRequest, opts ...grpc.CallOption) (ImageService_DownloadClient, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) Download(ctx context.Context, in *ImageDownloaderRequest, opts ...grpc.CallOption) (ImageService_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ImageService_serviceDesc.Streams[0], "/ImageService/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServiceDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ImageService_DownloadClient interface {
	Recv() (*ImageDownloaderResponse, error)
	grpc.ClientStream
}

type imageServiceDownloadClient struct {
	grpc.ClientStream
}

func (x *imageServiceDownloadClient) Recv() (*ImageDownloaderResponse, error) {
	m := new(ImageDownloaderResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility
type ImageServiceServer interface {
	//Server Stream
	Download(*ImageDownloaderRequest, ImageService_DownloadServer) error
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (UnimplementedImageServiceServer) Download(*ImageDownloaderRequest, ImageService_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageDownloaderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServiceServer).Download(m, &imageServiceDownloadServer{stream})
}

type ImageService_DownloadServer interface {
	Send(*ImageDownloaderResponse) error
	grpc.ServerStream
}

type imageServiceDownloadServer struct {
	grpc.ServerStream
}

func (x *imageServiceDownloadServer) Send(m *ImageDownloaderResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _ImageService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/image.proto",
}
