// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package imagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	//Bidirectional Stream
	Effect(ctx context.Context, opts ...grpc.CallOption) (ImageService_EffectClient, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) Effect(ctx context.Context, opts ...grpc.CallOption) (ImageService_EffectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ImageService_serviceDesc.Streams[0], "/ImageService/Effect", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServiceEffectClient{stream}
	return x, nil
}

type ImageService_EffectClient interface {
	Send(*ImageRequest) error
	Recv() (*ImageResponse, error)
	grpc.ClientStream
}

type imageServiceEffectClient struct {
	grpc.ClientStream
}

func (x *imageServiceEffectClient) Send(m *ImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageServiceEffectClient) Recv() (*ImageResponse, error) {
	m := new(ImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility
type ImageServiceServer interface {
	//Bidirectional Stream
	Effect(ImageService_EffectServer) error
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (UnimplementedImageServiceServer) Effect(ImageService_EffectServer) error {
	return status.Errorf(codes.Unimplemented, "method Effect not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_Effect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServiceServer).Effect(&imageServiceEffectServer{stream})
}

type ImageService_EffectServer interface {
	Send(*ImageResponse) error
	Recv() (*ImageRequest, error)
	grpc.ServerStream
}

type imageServiceEffectServer struct {
	grpc.ServerStream
}

func (x *imageServiceEffectServer) Send(m *ImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageServiceEffectServer) Recv() (*ImageRequest, error) {
	m := new(ImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Effect",
			Handler:       _ImageService_Effect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/image.proto",
}
